### ISSUE TITLE
magentoDataFixture should allow to use Module Prefix - Integrations Test 

### ISSUE THREAD

**Issue by larsroettig** [magento/community-features#113]
### Description (*)

As a Developer, we have different solutions to install Magento and Setup Projects. Currently, if the test fixtures place in the  **app/code/Module_Name**  and is installed over composer  is not possible to use annotations like **Magento_InventoryApi::Test/_files/products.php**

### Expected behavior (*)

Module annotations like  **Magento_InventoryApi::Test/_files/products.php** works and  **\Magento\TestFramework\Annotation\DataFixture** find the correct path for Integrations Test

### Benefits

As a developer, you can use the prefix to use **data fixture** from the core to test your own plugins and extensions  

### Additional information

```php
    /**
     * Old Fixture File place in testsuite
     * @magentoDataFixture Magento/Customer/_files/customer.php
     *
     * New Fixture File place in app/code
     * @magentoDataFixture Magento_InventoryApi::Test/_files/products.php
     *
     * @magentoDbIsolation disabled
     */
    public function testValidation()
```

**Comment by magento-engcom-team** [comment]
Hi @larsroettig. Thank you for your report. 
The issue has been fixed in magento/magento2#19679 by @larsroettig in 2.3-develop branch
Related commit(s):
 - [69ca6d7e23c01550bff752ae6244e1f64d5a7555](https://github.com/magento/magento2/commit/69ca6d7e23c01550bff752ae6244e1f64d5a7555)
 - [a055fa135b9e4b972d8dc4d0d222a928c3e3213d](https://github.com/magento/magento2/commit/a055fa135b9e4b972d8dc4d0d222a928c3e3213d)
 - [1bd5fffbbde24f181b37feee88368fc9180f9539](https://github.com/magento/magento2/commit/1bd5fffbbde24f181b37feee88368fc9180f9539)

The fix will be available with the upcoming 2.3.2 release.
