### ISSUE TITLE
Upgrade MySql search capability for more flexible options for users

### ISSUE THREAD

**Issue by Ctucker9233** [magento/community-features#286]
It still seems possible to use MySQL as a search engine according to the latest MySQL documentation. The MySQL search engine should be updated so that it is still an option for users who run on servers (particularly hosted servers) that do not support Elasticsearch.

**Comment by Ctucker9233** [comment]
@magento-devops Any thoughts?

**Comment by sivaschenko** [comment]
@Ctucker9233 thanks for the report! Mysql is not supported as a search engine in Magento 2.4.x. So such improvement cannot be delivered the Magento development branches.

Closing this issue as not actual. Do not hesitate to contact me on slack in case of any comments/question.

**Comment by hostep** [comment]
@sivaschenko : a client of ours is really not happy with this change.

He's currently using hosting in a high availability setup and according to the hosting company, he'll need 3 extra servers if he wants Elasticsearch to be setup in HA as well. The hosting strongly recommends against installing Elasticsearch on his existing frontend nodes because it could have a very high performance impact on them and our client really isn't happy to have to pay for 3 extra servers just because Magento decided to no longer support Mysql...

I know you guys are really trying to push for Magento Cloud which does support this out of the box, but you really need to consider people using Magento OS on other hosting environments and the extra costs which will come due to the new Elasticsearch requirement.

Just my 2 cents, it's not going to change anything I'm sure, so I don't know why I'm posting this but oh well ...
