### ISSUE TITLE
Change default value in QTY field in product view to 1

### ISSUE THREAD

**Issue by Eddcapone** [magento/community-features#299]
It makes no sense to set the value initially to 0, set it to 1 so that customers are not forced to change it to 1 all the time.

![image](https://user-images.githubusercontent.com/16349349/92939373-fe0ac800-f44d-11ea-9fff-f4d1be8980d3.png)

**Comment by sivaschenko** [comment]
@Eddcapone thanks for reporting. If your default Qty is 0 - it sounds more like a bug than a feature request, can you please provide the steps to reproduce.

**Comment by Eddcapone** [comment]
You just have to install magento 2 and create a product then view the product in frontend. QTY will be 0.

**Comment by mrtuvn** [comment]
![Screenshot_20201017-195005.png](https://user-images.githubusercontent.com/1908873/96337519-a3f8b600-103c-11eb-88df-62549554b64f.png)
Default qty is 1 not sure why this happen in your site

**Comment by Eddcapone** [comment]
You don't appear to use a fresh shop

**Comment by hostep** [comment]
@Eddcapone: I can't confirm. I've just setup a clean Magento 2.4.1 shop, created a category and product with enough stock. Visiting the product on the frontend shows the number 1 in the qty field:

<img width="1290" alt="Screenshot 2020-10-19 at 13 45 01" src="https://user-images.githubusercontent.com/85479/96446150-508b9100-1211-11eb-8add-5cdd8080fc01.png">

Have *you* already tried it in a clean setup? Because your screenshot also looks to be using a customised Magento...

**Comment by mrtuvn** [comment]
![Screenshot from 2020-10-19 21-23-49](https://user-images.githubusercontent.com/1908873/96463976-7df82f00-1251-11eb-80cd-5729f10b37c0.png)
here is details page in luma theme with latest code base

**Comment by Eddcapone** [comment]
Ok thank you all, then it looks like it is an old bug which they already fixed or a strange mistake. I also can't reproduce it anymore.
