### ISSUE TITLE
[Improvement] Add HTML attributes to containers

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/community-features#85]
Hello,

This is not an issue but an improvement. It would be nice to add HTML attributes to `containers` to layout files.

For example, if I want to create the following HTML output with a container:

```
<header class="header" id="header" data-sticky data-isheader="true">

</header>
```

I can specify tag, id and class but not the other attributes.

What do you think about it?

**Original Report**: https://github.com/magento/magento2/issues/13354 by @VincentMarmiesse

**Comment by max-atkins** [comment]
When will this improvement be available? It is better to create HTML through XML containers but I currently have to use custom classes with javascript to apply html attributes to these. It would be amazing to be able to add HTML attributes to containers

**Comment by joshdavenport** [comment]
Yeah this would be fantastic. I once needed to add custom microdata to existing containers and could only do so by either parsing output the dirty way or adding custom behaviour to container rendering. The custom behaviour needed custom XML which is invalid due to XSD validation. This kind of thing is a perfect use case for this feature.

**Comment by thomas-kl1** [comment]
See state of PR magento/magento2/pull/13355

**Comment by sivaschenko** [comment]
Please see the discussion in https://github.com/magento/magento2/pull/13355
